# json-schema-for-humans HTML config
template_name: flat
show_breadcrumbs: false
collapse_long_descriptions: false
collapse_long_examples: false
copy_css: true
copy_js: true
with_footer: true
footer_show_time: true
